name: "test_summarisation_bea5754180984615abdabc4f8ed68247"
backend: "python"
input [
  {
    name: "text"
    data_type: TYPE_STRING	
    dims: [-1]
  }
]
output [
  {
    name: "summary_text"
    data_type: TYPE_STRING	
    dims: [-1]
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]

